// Album data only - no logic
const albumData = [
    { 
        id: 1, 
        title: "The Fruit of Temptation Vol.1", 
        actress: "MINAMO",
        pages: 18, 
        release: "2025-03-13",
        tags: ["Traditional", "Kimono", "Elegant", "Cultural", "Japan"],
        images: 18,
        cover:   "https://lh3.googleusercontent.com/d/1KSUdzcxHYfBvNHvB5b92sKuWpbyuQHjI",
        albumImages: 
[
    "https://lh3.googleusercontent.com/d/1aPv9t-TfudTrcQza9wtkbE6P6YCKd5C7",
    "https://lh3.googleusercontent.com/d/1-Gd5y21xE7SdFKSxNQRIVb4Z2ZuH9YuM",
    "https://lh3.googleusercontent.com/d/1x3giArTYLEwmaCaIcoRENZ8pIaWLukzf",
    "https://lh3.googleusercontent.com/d/1OFL1_evJdKroKxyKMEh4cvx9aDKuTe22",
    "https://lh3.googleusercontent.com/d/174ScSbVOs8af2eycyr77_5rH1-81fgdk",
    "https://lh3.googleusercontent.com/d/14GMcv-sbtfwPhpdIJEa9GXyGeglDqNmf",
    "https://lh3.googleusercontent.com/d/1lptb3KOXALmOr7Jz8d3ZK1iPhWXDqxCz",
    "https://lh3.googleusercontent.com/d/1JYRJjAzeApWeZw7_Ap93Y2khmTGPuBbZ",
    "https://lh3.googleusercontent.com/d/1NGlqOMZ0OkduAelKAiN4Rah3y8bKnvqi",
    "https://lh3.googleusercontent.com/d/19R3o1rr0n3qYoTwgqNp8390-VxC2xc_6",
    "https://lh3.googleusercontent.com/d/1Xr86fjh96DJlbD_MWf7R9t_GrwNzSrzv",
    "https://lh3.googleusercontent.com/d/13xSSEQNXcKemxci9vdEpSXxmJbBPKuS9",
    "https://lh3.googleusercontent.com/d/1XlU3c0YW2imiwvNq2iKEGaPFfggBySJQ",
    "https://lh3.googleusercontent.com/d/1Q-guCv-yUsXC5FqQixHcp9P9Kiehv6mP",
    "https://lh3.googleusercontent.com/d/139ASG4XFYsSF-P9OzJNf1W--tHUmEWbU",
    "https://lh3.googleusercontent.com/d/12WRxH4sG_lnMxNOcrWRFImNeqRWn6iqE",
    "https://lh3.googleusercontent.com/d/1lhe6JCmadbAtz41lcY6wtzJv26TpLsnj"
]    },

    { 
        id: 2, 
        title: "The Fruit of Temptation Vol.2",  
        actress: "MINAMO",
        pages: 24, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 24,
        cover: "https://lh3.googleusercontent.com/d/1GJmdUQ-lkeB43kZcSMkIGI4wKQZYCggq",
        albumImages: 
        [
    "https://lh3.googleusercontent.com/d/1bV-bbhBrbWgo-eTy96sM8ZSKwuCIxdWv",
    "https://lh3.googleusercontent.com/d/15h-vSw4tgmp92ujuRxNGtX1zRZ4CB3_1",
    "https://lh3.googleusercontent.com/d/1CXStzqir4LWVEayEKJRX9XODkfIxmG1y",
    "https://lh3.googleusercontent.com/d/1UrPInhvPb7DaIwwIHGOnA1WM6htZ9ETP",
    "https://lh3.googleusercontent.com/d/1GrklawAKbKe5SxNIHqzvCa7NSMfV1faO",
    "https://lh3.googleusercontent.com/d/1I8KX9kPtqBztblogygp4OlR3GTRlL36V",
    "https://lh3.googleusercontent.com/d/19TUqGK1Tzt4uerQDUc4VvOluiJuBUWDn",
    "https://lh3.googleusercontent.com/d/1e2gaUkC-Vp5jV6b2wx2-RHG4CZaNiEKe",
    "https://lh3.googleusercontent.com/d/1nMezlOdVND5FPi_IO-MCQHpjMqrB4PYb",
    "https://lh3.googleusercontent.com/d/1o_hCdNIBweXS48fuDpkFCIUOwYSn6fE2",
    "https://lh3.googleusercontent.com/d/1mq9oJAg6CnIHVlmn1Woytb1SasOWj5-n",
    "https://lh3.googleusercontent.com/d/1oh1RGrTErFseOrOQVO7olUcKs2nrZSP_",
    "https://lh3.googleusercontent.com/d/1AasBzRiNGaXRBRIbQTbD8b4r38UzG7Nm",
    "https://lh3.googleusercontent.com/d/1dSfq2T8QXg-p5H5i-MkknM1gmJQEWuYd",
    "https://lh3.googleusercontent.com/d/1mm0ETsGuQ4ItHnYaK7g8A2n6B0GAwRHB",
    "https://lh3.googleusercontent.com/d/1CsA7HUZOjLwCaaxxBK5hCY7N33ym671f",
    "https://lh3.googleusercontent.com/d/11vzHxgnhDQ2SVGmljIQ6dHx8rrHu5yqa",
    "https://lh3.googleusercontent.com/d/11OVBDfuEe4VaXYdUgyoqXoXAhuYm2dgO",
    "https://lh3.googleusercontent.com/d/1-c9gO4g_8G-P2iqRXW4lUhQcuApq7yPN",
    "https://lh3.googleusercontent.com/d/1Ag1vHAEqk-GVilcNIhVX0Wqa9gu3FsYy",
    "https://lh3.googleusercontent.com/d/171YFcmJidiB3HgFZS6JQ_jncciGXg4Re",
    "https://lh3.googleusercontent.com/d/13HOeyfyQHImEUHw-aIwp9nk4YqYlxCcK",
    "https://lh3.googleusercontent.com/d/1sbel48rn4VZuyC_ImLKE7RNBWys45Qnl"
]
    },
    { 
        id: 3, 
        title: "The Fruit of Temptation Vol.3",  
        actress: "MINAMO",
        pages: 22, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 22,
        cover: "https://lh3.googleusercontent.com/d/1h8IsWoItiM46yrFoZl6xWLms9hWOnBjt",
        albumImages: 
        [
    "https://lh3.googleusercontent.com/d/1jA4sgre6bTXNT050wzc7hGkjOOOx9uho",
    "https://lh3.googleusercontent.com/d/1mVyU-zBn_Sd_7daO_5dXImDiYCsXbyhP",
    "https://lh3.googleusercontent.com/d/1aSbh3xq09s1kvkJX6Vxyza-pDrB4S5jZ",
    "https://lh3.googleusercontent.com/d/12zSyasl9m0m49AC5AXd1pMgSwRa5jiI5",
    "https://lh3.googleusercontent.com/d/1KVr-QT4mIaXvntPIr6VR37XMbvhWHC2j",
    "https://lh3.googleusercontent.com/d/1EfjoqnEOMmVx1jkhNYIykuCDg0PXqh7x",
    "https://lh3.googleusercontent.com/d/1BaJmG8fX2XzRoQeV_rTxki7rreE2NidG",
    "https://lh3.googleusercontent.com/d/12Vh2_yhm9zNnDoS_9npaQEw66lczAZAR",
    "https://lh3.googleusercontent.com/d/1ZX-2WsulPs_Z6sWizw6Ze4bn6xN37c5h",
    "https://lh3.googleusercontent.com/d/1ozkG4aksMb6iOxLJfBbDVVWaT4pYFF1w",
    "https://lh3.googleusercontent.com/d/1IeKLX8s6TUZ4D8wY5YHGyqNSjs3G5Ljl",
    "https://lh3.googleusercontent.com/d/1dKf_fFRd6KUpLIZboJV-6F128eo2krNJ",
    "https://lh3.googleusercontent.com/d/1bODBnY0rj5SXLnQBfBiJM5trawM68lAV",
    "https://lh3.googleusercontent.com/d/1TAJFo-rnN4OLSyycPCMYop8cOWsfa3ti",
    "https://lh3.googleusercontent.com/d/1oQckmnL1Cg2X4y3YR-2gYRPDhMtjW9Ui",
    "https://lh3.googleusercontent.com/d/1gnI7qysbk9nn_IAPg1O3CKQgyIUOMZr3",
    "https://lh3.googleusercontent.com/d/1U7_txIpG5uJ7DYMIRi3Puvf-asnVPmfQ",
    "https://lh3.googleusercontent.com/d/1HtBIpX7tYt9zkL-Ijva3DUra5Tg92YVB",
    "https://lh3.googleusercontent.com/d/1-QW5gZwqxa1qXyZp0_NVQp-uYmXotlsD",
    "https://lh3.googleusercontent.com/d/1Gzux5-udLVQCnPmEHusD4gujkdKzU20r",
    "https://lh3.googleusercontent.com/d/17xCWZkZejXp8A-49l1Vmg2tzcaR3sDuD"
]
    },
       { 
        id: 4, 
        title: "The Fruit of Temptation Vol.4",  
        actress: "MINAMO",
        pages: 16, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 16,
        cover: "https://lh3.googleusercontent.com/d/1mmvCZMDNX_HmOPBwm_o_cOECp94ItSkj",
        albumImages: 
       [
    "https://lh3.googleusercontent.com/d/1gD6jgdkYPRhMjsdLupaKRK1dmYANwRTo",
    "https://lh3.googleusercontent.com/d/13SMO_GJhUIvM2osCQk7qJJx72GVuTPfo",
    "https://lh3.googleusercontent.com/d/1imtAzcs5nvBcbhpZtT8u32SDcqRkb2P8",
    "https://lh3.googleusercontent.com/d/1LHAsjzvqP8CQL9QRCv_-zEFTbagkGu1t",
    "https://lh3.googleusercontent.com/d/17QqZSImYZCp0TP1Kxi-nyycwXdAbTCf7",
    "https://lh3.googleusercontent.com/d/130L2y0vI86PqV2OFB2K-yLsEhFzGPF1Y",
    "https://lh3.googleusercontent.com/d/13jnwy1zAERhwlOWp4PGwlc6CtEm8gd8W",
    "https://lh3.googleusercontent.com/d/1Nq6CeqQHHERqzkdu3_VBnm3JU3CfnZ7D",
    "https://lh3.googleusercontent.com/d/14N6gpWcMHvItdLnJT4jfzhKs_KSNx6Ej",
    "https://lh3.googleusercontent.com/d/1h_AWMV1ZbaSUEPeB5JVoSPckKNKnm2dv",
    "https://lh3.googleusercontent.com/d/1ZmsnVv4NRnekeE4XtTAuK9ezIUP7L4or",
    "https://lh3.googleusercontent.com/d/1TJuKMT0Teu2VD6_g6yta0Jen4c6ZTBgE",
    "https://lh3.googleusercontent.com/d/1Ao_VRI1VafOk1r9V-OaaQIRIlijaMkP6",
    "https://lh3.googleusercontent.com/d/1JDkn256SjJVQXbDPHE9c11aN5kVLeLOe",
    "https://lh3.googleusercontent.com/d/1N_LuXowmDgZfwvqvD6VtVBba9IQnYEmm"
]
    },
    { 
        id: 5, 
        title: "The Fruit of Temptation Vol.5",  
        actress: "MINAMO",
        pages: 14, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 14,
        cover: "https://lh3.googleusercontent.com/d/1cw0eXeDJ3kPH-ogvMwRfdPXgAVA0hCMW",
        albumImages: 
       [
    "https://lh3.googleusercontent.com/d/1wWu32dK6Wx9c6sf1KCkc8iAOjg2fI4ez",
    "https://lh3.googleusercontent.com/d/1QLgnZetbacTUDEz1IN4Zz5xlUKhhC_1M",
    "https://lh3.googleusercontent.com/d/1RRkIAxqIW5DGuoxL20DMkwh4mHfiSc_t",
    "https://lh3.googleusercontent.com/d/1Lesnj8nBGadPA0ooaaKFSNKaui3Ke4Cn",
    "https://lh3.googleusercontent.com/d/1SFPeG0nIfSLCQiUPMlxn0Pan2j2EuuIX",
    "https://lh3.googleusercontent.com/d/1FKakdN59fTN1kQlWgDQIESn1h3ORz9fL",
    "https://lh3.googleusercontent.com/d/1Kjvg_fcDOmH0GvTAPEghQUtVQkOp2r6q",
    "https://lh3.googleusercontent.com/d/1iP2wJ65IJB8oBMjUarEL-mdZG76_Vxvq",
    "https://lh3.googleusercontent.com/d/1vYBpOCj8anMsDAX_3QPkE8gOEf9nTLuD",
    "https://lh3.googleusercontent.com/d/1taZcuNrBStpSLVxoats1RnGSPONzqBDq",
    "https://lh3.googleusercontent.com/d/1mTuRk8xWg3SBo_uiNOsARx10C_pgjlVT",
    "https://lh3.googleusercontent.com/d/1S0KPFi6iOlD0M26dj-RJQBiPbc6j3aS9",
    "https://lh3.googleusercontent.com/d/1ojHxFAYgCJSHMrSnZlEcH2852x9xBl-y"
]
    },
    { 
        id: 6, 
        title: "The Fruit of Temptation Vol.6",  
        actress: "MINAMO",
        pages: 9, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 9,
        cover: "https://lh3.googleusercontent.com/d/1uOUM7Pe9eGWr-1PGpMEOT7kryXJIZgyk",
        albumImages: 
       [
    "https://lh3.googleusercontent.com/d/1BQMMBacM6u-BC-SmAkG0v_XsAWNYp-3Y",
    "https://lh3.googleusercontent.com/d/16rp5MBUzTCPuq3OUPZ-KETtbuwz7_Xtf",
    "https://lh3.googleusercontent.com/d/1ZE9lt9R0Fuw8l25tvDdaGFl5v-Svvo6x",
    "https://lh3.googleusercontent.com/d/1c90pzBvxeSzbMVY0ddEMlNAJbJhJWH36",
    "https://lh3.googleusercontent.com/d/1uViQeW_6FMh5ZtK8tL_5_8h2C8Tukkgy",
    "https://lh3.googleusercontent.com/d/1ArKoUfIBBeMZ2J0GHB5RlKSvqYHjZ7kI",
    "https://lh3.googleusercontent.com/d/1Q4wQ6jAYZVC8z12sMXndkbvG9mT-g_eG",
    "https://lh3.googleusercontent.com/d/1dCP9aIL-O22pE6cBcJga54YBGH1DGVDy"
]
    },
    { 
        id: 7, 
        title: "The Fruit of Temptation Vol.7",  
        actress: "MINAMO",
        pages: 20, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 20,
        cover: "https://lh3.googleusercontent.com/d/14TNdbbZjbljckBgkE2dpucmXteL6Blu8",
        albumImages: 
       [
    "https://lh3.googleusercontent.com/d/1bHzrdUAz3hYQgXXHSU9e_y8t1eupeZTI",
    "https://lh3.googleusercontent.com/d/1wSUkRx0AUDWD9WlvDXsXygh0zHACaObX",
    "https://lh3.googleusercontent.com/d/1BD1okwsaD_NN5wQePDU4eqRXS5jmnV8C",
    "https://lh3.googleusercontent.com/d/15UgG8GN_MzqbqBHvR5YHZXC-Ep56g20n",
    "https://lh3.googleusercontent.com/d/1SoKouWgfOJEp8u7-TkVoSrVfDZb5jK7L",
    "https://lh3.googleusercontent.com/d/1ZmkuV0O5aV6xd0DxRE1euDf9v7sz-9a4",
    "https://lh3.googleusercontent.com/d/1_R2TfgCEqtx_SPobpccu2Rb1_HXtV3TE",
    "https://lh3.googleusercontent.com/d/1m94pqrdO0d6bKFFyQG18OWgo37OtcLsL",
    "https://lh3.googleusercontent.com/d/1um7Lu4R0onphGRshumse8zGmvcgCYQ3E",
    "https://lh3.googleusercontent.com/d/1dzHXcdx8Ap2bs-8nd87i3U8DPNgnIlRh",
    "https://lh3.googleusercontent.com/d/1OfnRWi91xCQEdY-a4bcV-B_C3dTw1JsB",
    "https://lh3.googleusercontent.com/d/1B5DV2Ol59cjLfnNs4cWTMWDeztHhim_c",
    "https://lh3.googleusercontent.com/d/1F3RGNcv_6YV9acAZxHnNuDc3-Z5r0lYm",
    "https://lh3.googleusercontent.com/d/1i69Z4kOb2JwgwEZeNuHCXSrZenc7TJzm",
    "https://lh3.googleusercontent.com/d/1wt5am_uNj1bpyN40xwOQsYLF2s88jueT",
    "https://lh3.googleusercontent.com/d/1BEKKveQaB7kSpUp9Ch_XXxBuqrPSq7Of",
    "https://lh3.googleusercontent.com/d/17E5-yWGQks8Bs4dNE_nvwopRrNbxdQX6",
    "https://lh3.googleusercontent.com/d/1B92wHXSZbSaFQ_FTQN192htc-I9p7YPs",
    "https://lh3.googleusercontent.com/d/1Jkz6lA_d-GpfdRXhRHOl51WjvFyGSzrB"
]
    },
    { 
        id: 8, 
        title: "The Fruit of Temptation Vol.8",  
        actress: "MINAMO",
        pages: 25, 
        release: "2025-03-13",
        tags: ["Summer", "Beach", "Swimsuit", "Sunset", "Ocean"],
        images: 25,
        cover:  "https://lh3.googleusercontent.com/d/1NrmqHU04TWaypZ0RAuqd2C4hrH7pZveA",
        albumImages: 
       [
    "https://lh3.googleusercontent.com/d/1AQP5vTILLKeF8O3i0VJmIHUz-u8QaCWA",
    "https://lh3.googleusercontent.com/d/1QLU19ioGnguDdZfcfaHZIBTJbyzqLNkY",
    "https://lh3.googleusercontent.com/d/10lR-e1ym-qpTdLnE3ZrjCYwkdNDfXeRH",
    "https://lh3.googleusercontent.com/d/1gbdYV4K3fpDx0H8kCNZeXNzXj5nx0QLj",
    "https://lh3.googleusercontent.com/d/1OvAHKmWmTexqMqFwtAnroIuaKDbkTVTj",
    "https://lh3.googleusercontent.com/d/10n5rHFODfNfL0EibObvKAoszwjbbqsXC",
    "https://lh3.googleusercontent.com/d/1quWrj9KWoZ75i7jPFYollSc1zHd6Atbr",
    "https://lh3.googleusercontent.com/d/1--WqPPy1hthShi__ipdTbJaNz10V9pxr",
    "https://lh3.googleusercontent.com/d/1gIeMTKoDPub0Y-D--ra2n_f3tWHLiXis",
    "https://lh3.googleusercontent.com/d/1sn7A6IfchSu_FRS7ndmY3CSL2HUF1vPf",
    "https://lh3.googleusercontent.com/d/1Pr6fw9mBXb9b2XtA4htpWLQWVfAdXaQ2",
    "https://lh3.googleusercontent.com/d/1W9ZJJKKqLA2-g6rNTnFlrHrANt0Sihad",
    "https://lh3.googleusercontent.com/d/1ieytUoT-bc0Fw5We7bTIETlK5PPbTMBP",
    "https://lh3.googleusercontent.com/d/1PnaBvToOp6aav4ZSTMsuQUxPwXG5LfYV",
    "https://lh3.googleusercontent.com/d/1fYTxT9B7zPe98b_XNQN1J7ojlwpitDVy",
    "https://lh3.googleusercontent.com/d/1VBAEg2luWlDy8EAQPdkXN94kNYcf_sm3",
    "https://lh3.googleusercontent.com/d/1McyLveMFG2LrTrTcP-4rzEbU19XKNOAr",
    "https://lh3.googleusercontent.com/d/15DBvlnIQ7UI3lsPYMtfYXwdfeDlPbR-S",
    "https://lh3.googleusercontent.com/d/1__LdH5KlPvZW7ZCRGJ_guW__5T9up-KM",
    "https://lh3.googleusercontent.com/d/1Go6grsTjKxSPYRMMpOqnn0SCOW8qXn5n",
    "https://lh3.googleusercontent.com/d/1Xo9OeyKrzIIv5iNMnP-Y2wwA9PY7iKZY",
    "https://lh3.googleusercontent.com/d/1_jBjbb8Liboj7oSEQhNTKSZ_NF1hO9Mp",
    "https://lh3.googleusercontent.com/d/136xMsIMjVS59qC2KZb51rNegbrH4uHgv",
    "https://lh3.googleusercontent.com/d/13uArZLwbbdF2ZCSGR7NIB2k0enKMGFT_"
]
    }
    
];


